version: '2'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE=azure
      REGISTRY_STORAGE_AZURE_ACCOUNTNAME="builder176wv15xp"
      REGISTRY_STORAGE_AZURE_ACCOUNTKEY="2OocSCk0fmoRGO48oRd1IMWalYj7cuDqwJ5stCEIN2sJHhlKBtLgll36W21Su"
      REGISTRY_STORAGE_AZURE_CONTAINER="registry"
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./certs:/certs
      - ./auth:/auth
