version: '2'

services:
    mongodb:
        image: mongo:3.2.5
        volumes_from: 
            - container:mongo-data
        command:
            - --storageEngine=wiredTiger
        ports:
            - "27017"
        networks:
            - front

    test:
        stdin_open: true
        tty: true
        image: python:2.7.11
        command:
            - bash
        depends_on:
            - falcon
        networks:
            - front

    falcon:
        image: test-falcon
        ports:
            - "8020"
        depends_on:
             - mongodb
        networks:
            - front

    nginx:
        image: nginx:alpine
        ports:
            - "80"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - falcon
        networks:
            - front

networks:        
    front:
        driver: overlay

