version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  api:
    build:
      context: .
      dockerfile: autopull.Dockerfile
    image: trendi_api:latest
    ports: 
      - "8888:8888"
    command: gunicorn -b :8888 -w 10 -k gevent --timeout 40 trendi.pipeline.app:api
    environment:
      - DEBUG=1
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /data:/data
  mongo:
    image: mongo:latest
  redis:
    image: redis:latest
  dl_worker:
    image: trendi_api:latest
    environment:
      - DEBUG=1
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: rqworker -u redis://redis:6379 fingerprinter4db
  annoy_worker:
    image: trendi_api:latest
    volumes:
        - /data/forest:/root/forest
    environment:
      - FOREST_DIR=/root/forest/
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: rqworker -u redis://redis:6379 annoy annoy_forest

